# Generated by Django 3.2.5 on 2021-07-16 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awwardsapp', '0002_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='average',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=20),
        ),
    ]
